### ISSUE TITLE
Fechamento inesperado

### ISSUE THREAD

**Issue by natanmorais** [AshaSoftware/StudyDay#9]
Primeira vez que rodei, fui criar uma matéria e setei todas as opções, quando fui salvar o app fechou com o erro em anexo. Agora toda vez que abro o app já dá o erro logo de cara.
![captura de tela de 2015-11-06 10 04 13](https://cloud.githubusercontent.com/assets/13126190/10996665/4b5e46ae-846e-11e5-9b26-7dfdf78dff46.png)

**Comment by ghost** [comment]
Qual a versão do android?

**Comment by natanmorais** [comment]
da máquina virtual?
o 4.alguma coisa
